spring:
    application:
        name: mdfs

mdfs:
    path: ${user.home}/mdfs
    syncBackup: false
    autoMd5: true
    group: C8090
    backupUrl: http://localhost:8091/upload
    downloadUrl: http://localhost:8090/download

rocketmq:
    name-server: localhost:9876
    producer:
        group: mdfs-producer

server:
    port: 8090