spring:
    application:
        name: midnight-dfs
    web:
        resources:
            static-locations: classpath:/static/,classpath:/resources/static/


    servlet:
        multipart:
            max-file-size: 10MB

mdfs:
    path: ${user.home}/mdfs
    isSync: true
    backupUrl: http://localhost:8081/upload

logging:
    level:
        root: info
        com: info
        javax: info
        sun: info